import React from 'react';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';
import Link from '@docusaurus/Link';
import {plugins} from '@site/src/data/plugins';
import {goldenBuilds} from '@site/src/data/builds';
import {compatibilityRows} from '@site/src/data/compatibility';
import styles from './styles.module.css';
export default function Dashboard(){const verified=plugins.filter(p=>p.status==='verified').length;const testing=plugins.filter(p=>p.status==='testing').length;const confidence=Math.round(compatibilityRows.reduce((a,p)=>a+p.confidence,0)/compatibilityRows.length);return <Layout title="Operations Dashboard" description="Live Project Sentinel status dashboard."><main className={styles.page}><header className={styles.hero}><div className="container"><div><span>Sentinel operations center</span><Heading as="h1">System Dashboard</Heading><p>The current state of the verified build, registry, testing program and documentation platform.</p></div><div className={styles.live}><i/>All systems operational</div></div></header><section className={styles.body}><div className="container"><div className={styles.metrics}><article><span>Registry records</span><strong>{plugins.length}</strong><small>{verified} verified</small></article><article><span>Golden builds</span><strong>{goldenBuilds.length}</strong><small>Current baseline active</small></article><article><span>Matrix confidence</span><strong>{confidence}%</strong><small>{compatibilityRows.length} tracked components</small></article><article><span>Testing queue</span><strong>{testing}</strong><small>Awaiting approval</small></article></div><div className={styles.grid}><article className={styles.primary}><span>Current verified environment</span><Heading as="h2">Legacy 3788 Golden Build</Heading><dl><div><dt>GTA V Legacy</dt><dd>1.0.3788.0</dd></div><div><dt>RAGE Plugin Hook</dt><dd>1.130.1406.17682</dd></div><div><dt>LSPDFR</dt><dd>0.4.9 · 0.4.9572</dd></div><div><dt>Build state</dt><dd className={styles.good}>Verified</dd></div></dl><Link to="/builds">Open build archive →</Link></article><article><span>Quick actions</span><Heading as="h2">Plan, diagnose, deploy</Heading><div className={styles.actions}><Link to="/planner"><b>Build Planner</b><small>Generate a compatible patrol setup.</small></Link><Link to="/troubleshooter"><b>Troubleshooting Wizard</b><small>Follow symptoms to a repair path.</small></Link><Link to="/checklist"><b>Installation Checklist</b><small>Track progress locally in your browser.</small></Link><Link to="/compatibility"><b>Compatibility Center</b><small>Inspect every tracked component.</small></Link></div></article></div><section className={styles.health}><div><span>Verified plugin health</span><strong>{verified}/{plugins.length}</strong></div><div className={styles.track}><i style={{width:`${Math.round(verified/plugins.length*100)}%`}}/></div><p>Only verified entries are approved for the strict Golden Build. Documented, testing and research records remain visible so the site clearly distinguishes evidence from plans.</p></section></div></section></main></Layout>}
