import React,{useEffect,useMemo,useState} from 'react';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';
import Link from '@docusaurus/Link';
import useBaseUrl from '@docusaurus/useBaseUrl';
import styles from './styles.module.css';

export default function Watcher(){
 const reportUrl=useBaseUrl('/data/watcher-report.json'); const [report,setReport]=useState(null); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('review');
 useEffect(()=>{fetch(reportUrl).then(r=>r.json()).then(setReport).catch(()=>setReport({counts:{tracked:0,reachable:0,updated:0,unreachable:0,archived:0,needsReview:0},items:[]}));},[reportUrl]);
 const items=useMemo(()=>{const all=report?.items||[];return all.filter(x=>{const text=`${x.name} ${x.category} ${x.note}`.toLowerCase();const q=text.includes(query.toLowerCase());const f=filter==='all'||(filter==='review'&&(x.change!=='none'||x.note))||(filter==='updated'&&['updated','page-changed'].includes(x.change))||(filter==='unreachable'&&x.change==='unreachable')||(filter==='archived'&&x.archived);return q&&f;});},[report,query,filter]);
 const c=report?.counts||{};
 return <Layout title="Sentinel Watcher" description="Automated monitoring reports for the LSPDFR mod ecosystem."><main className={styles.page}><header className={styles.hero}><div className="container"><span>Project Sentinel maintenance system</span><Heading as="h1">Sentinel Watcher</Heading><p>Scheduled checks for tracked mod pages, GitHub releases, broken links, archived repositories and changes that need human review.</p><div className={styles.actions}><a href="https://github.com/SmarshMello/Project-Sentinel/actions/workflows/sentinel-watcher.yml">Open workflow</a><Link to="/plugins">Browse database</Link></div></div></header><section className="container"><div className={styles.notice}><b>Review-first automation</b><span>Watcher 0.1 never edits or publishes database records automatically. It produces a report artifact for you to inspect.</span></div><div className={styles.metrics}>{[['Tracked',c.tracked],['Reachable',c.reachable],['Changed',c.updated],['Unreachable',c.unreachable],['Archived',c.archived],['Needs review',c.needsReview]].map(([l,v])=><article key={l}><span>{l}</span><strong>{v??'—'}</strong></article>)}</div><div className={styles.toolbar}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search monitored projects…"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="review">Needs review</option><option value="all">All tracked</option><option value="updated">Changed</option><option value="unreachable">Unreachable</option><option value="archived">Archived</option></select></div><div className={styles.meta}>Last committed scan: {report?.checkedAt?new Date(report.checkedAt).toLocaleString():'Loading…'} · Showing {items.length} records</div><div className={styles.list}>{items.map(item=><article key={item.id}><div><span className={`${styles.state} ${styles[item.change]||''}`}>{item.change==='none'?'monitored':item.change}</span><Heading as="h2">{item.name}</Heading><p>{item.category} · Expected: {item.expectedVersion}</p>{item.note&&<small>{item.note}</small>}</div><dl><div><dt>HTTP</dt><dd>{item.httpStatus??'—'}</dd></div><div><dt>Latest release</dt><dd>{item.latestRelease||'Not detected'}</dd></div><div><dt>Sentinel Police</dt><dd>{item.sentinelPolice?'Yes':'No'}</dd></div></dl><a href={item.finalUrl||item.url}>Open official source →</a></article>)}</div>{!items.length&&<div className={styles.empty}>No records match this view. Run the workflow manually to generate a fresh report.</div>}</section></main></Layout>
}
