import React,{useEffect,useMemo,useState} from 'react';
import BrowserOnly from '@docusaurus/BrowserOnly';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';
import Link from '@docusaurus/Link';
import useBaseUrl from '@docusaurus/useBaseUrl';
import {answerExpertQuestion,expertExamples,statusMeta} from '@site/src/data/expertEngine';
import styles from './styles.module.css';

function WatcherBadge({p}){if(!p.watcherTracked)return <span className={styles.untracked}>Not monitored</span>;const w=p.watcher;return <span className={w.status==='healthy'?styles.liveGood:styles.liveWarn}>{w.status==='healthy'?'Live healthy':String(w.status||'unknown').replaceAll('-',' ')}</span>}
function Card({p}){const health=p.watcher?.healthScore;return <article className={styles.card}><div className={styles.cardHead}><div><small>{p.category}</small><h3>{p.name}</h3></div><span>{statusMeta[p.status]?.label||p.status}</span></div><p>{p.description}</p><dl><div><dt>Version</dt><dd>{p.watcher?.detectedVersion||p.version||'Not locked'}</dd></div><div><dt>Registry confidence</dt><dd>{p.confidence??'—'}%</dd></div><div><dt>Watcher health</dt><dd>{Number.isFinite(health)?`${health}%`:'Not monitored'}</dd></div><div><dt>Source</dt><dd><WatcherBadge p={p}/></dd></div></dl>{p.watcher?.intelligence?.recommendation&&<aside>{p.watcher.intelligence.recommendation}</aside>}{p.note&&<aside>{p.note}</aside>}<footer><Link to={p.profile}>Open profile →</Link>{p.guide&&<Link to={p.guide}>Guide</Link>}</footer></article>}
function WatcherPanel({w}){if(!w)return null;return <section className={styles.watcherPanel}><div><small>Live Watcher intelligence</small><h2>{w.tracked} monitored result{w.tracked===1?'':'s'} used</h2><p>{w.degraded.length?`${w.degraded.length} source signal${w.degraded.length===1?'':'s'} currently need attention.`:'All matched monitored sources are healthy.'}</p></div><div><span><b>{w.updates.length}</b> update signals</span><span><b>{w.degraded.length}</b> degraded sources</span></div></section>}
function Result({r}){if(!r)return <div className={styles.empty}><b>SE</b><Heading as="h2">Grounded answers, not guesses.</Heading><p>Ask about a version, dependency, install order, compatibility combination, category, or troubleshooting symptom.</p></div>;return <div className={styles.result}><section className={`${styles.verdict} ${styles[r.tone]||''}`}><small>Sentinel verdict</small><Heading as="h2">{r.verdict}</Heading><p>{r.summary}</p></section><WatcherPanel w={r.watcher}/>{r.warnings?.length>0&&<section className={styles.alert}><h2>Why Sentinel flagged it</h2><ul>{r.warnings.map(x=><li key={x}>{x}</li>)}</ul></section>}{r.installPlan?.length>0&&<section><h2 className={styles.sectionTitle}>Recommended install order</h2><ol className={styles.installPlan}>{r.installPlan.map((step,i)=><li key={step.project.id}><span>{i+1}</span><div><Link to={step.project.profile}>{step.project.name}</Link><small>{step.reason} · {step.project.version||'Version not locked'}</small></div></li>)}</ol></section>}{r.projects?.length>0&&<section><h2 className={styles.sectionTitle}>{r.type==='search'?'Registry matches':'Project intelligence'}</h2><div className={styles.cards}>{r.projects.map(p=><Card key={p.id} p={p}/>)}</div></section>}{r.dependencies?.some(x=>x.items.length)&&<section><h2 className={styles.sectionTitle}>Dependencies</h2><div className={styles.deps}>{r.dependencies.filter(x=>x.items.length).map(x=><article key={x.plugin.id}><strong>{x.plugin.name}</strong><ul>{x.items.map(d=><li key={d.name}>{d.project?<Link to={d.project.profile}>{d.name}</Link>:d.name}</li>)}</ul></article>)}</div></section>}{r.type==='doctor'&&<section className={styles.doctor}><div><small>Next best action</small><h2>Continue in Sentinel Doctor</h2><p>Add versions, symptoms, logs, and repair rules.</p></div><Link className="button button--primary" to="/doctor">Open Doctor →</Link></section>}<div className={styles.source}>Sources: Sentinel Unified Registry + latest published Watcher report · Local browser engine · No external AI API</div></div>}
function App(){const reportUrl=useBaseUrl('/data/watcher-report.json');const[q,setQ]=useState(''),[r,setR]=useState(null),[history,setHistory]=useState([]),[report,setReport]=useState(null),[liveState,setLiveState]=useState('loading');useEffect(()=>{let active=true;fetch(`${reportUrl}?expert=${Date.now()}`,{cache:'no-store'}).then(x=>{if(!x.ok)throw new Error('report');return x.json();}).then(data=>{if(active){setReport(data);setLiveState('ready');}}).catch(()=>active&&setLiveState('offline'));return()=>{active=false};},[reportUrl]);const related=useMemo(()=>r?.mentions?.length?[`What version of ${r.mentions[0].name} should I use?`,`What does ${r.mentions[0].name} require?`,`What is the install order for ${r.mentions[0].name}?`]:expertExamples.slice(0,3),[r]);function ask(v=q){const clean=v.trim();if(!clean)return;const ans=answerExpertQuestion(clean,report);setR(ans);setQ(clean);setHistory(h=>[{q:clean,v:ans.verdict},...h.filter(x=>x.q!==clean)].slice(0,6));}return <Layout title="Sentinel Expert" description="Registry and Watcher-grounded LSPDFR answers"><main className={styles.page}><header className={styles.hero}><div><small>Sentinel Intelligence Layer · Step 2</small><Heading as="h1">Ask Sentinel.</Heading><p>Structured answers from the Unified Registry and the latest published Watcher scan—without invented compatibility claims or a paid API.</p><section><span>59 registry projects</span><span className={liveState==='ready'?styles.heroLive:styles.heroMuted}>{liveState==='ready'?'Watcher connected':liveState==='loading'?'Connecting Watcher…':'Registry-only mode'}</span><span>Install planning</span><span>Compatibility reasoning</span><span>Doctor routing</span></section></div></header><div className={styles.layout}><aside className={styles.sidebar}><section><b>Try a verified question</b>{expertExamples.map(x=><button key={x} onClick={()=>ask(x)}>{x}</button>)}<button onClick={()=>ask('What is the install order for EUP Menu?')}>What is the install order for EUP Menu?</button></section>{history.length>0&&<section><b>Session history</b>{history.map(x=><button key={x.q} onClick={()=>ask(x.q)}><strong>{x.q}</strong><small>{x.v}</small></button>)}</section>}</aside><section className={styles.main}><div className={styles.ask}><textarea rows="3" maxLength="500" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask();}}} placeholder="Ask about a plugin, version, install order, dependency, conflict, category, or crash…"/><footer><span>{q.length}/500 · Enter to ask</span><button disabled={q.trim().length<3} onClick={()=>ask()}>Ask Sentinel</button></footer></div><Result r={r}/>{r&&<section className={styles.related}><b>Related questions</b><div>{related.map(x=><button key={x} onClick={()=>ask(x)}>{x}</button>)}</div></section>}</section></div></main></Layout>}
export default function SentinelAI(){return <BrowserOnly fallback={<Layout title="Sentinel Expert"><main className="container margin-vert--xl">Loading Sentinel intelligence…</main></Layout>}>{()=><App/>}</BrowserOnly>}
