import React,{useMemo,useState} from 'react';
import BrowserOnly from '@docusaurus/BrowserOnly';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';
import Link from '@docusaurus/Link';
import {answerExpertQuestion,expertExamples,statusMeta} from '@site/src/data/expertEngine';
import styles from './styles.module.css';

function Card({p}){return <article className={styles.card}><div className={styles.cardHead}><div><small>{p.category}</small><h3>{p.name}</h3></div><span>{statusMeta[p.status]?.label||p.status}</span></div><p>{p.description}</p><dl><div><dt>Version</dt><dd>{p.version||'Not locked'}</dd></div><div><dt>Confidence</dt><dd>{p.confidence??'—'}%</dd></div><div><dt>Developer</dt><dd>{p.developer||'Unknown'}</dd></div><div><dt>Golden Build</dt><dd>{p.goldenBuild?'Included':'Not included'}</dd></div></dl>{p.note&&<aside>{p.note}</aside>}<footer><Link to={p.profile}>Open profile →</Link>{p.guide&&<Link to={p.guide}>Guide</Link>}</footer></article>}
function Result({r}){if(!r)return <div className={styles.empty}><b>SE</b><Heading as="h2">Grounded answers, not guesses.</Heading><p>Ask about a version, dependency, compatibility combination, category, or troubleshooting symptom.</p></div>;return <div className={styles.result}><section className={`${styles.verdict} ${styles[r.tone]||''}`}><small>Sentinel verdict</small><Heading as="h2">{r.verdict}</Heading><p>{r.summary}</p></section>{r.warnings?.length>0&&<section className={styles.alert}><h2>Why Sentinel flagged it</h2><ul>{r.warnings.map(x=><li key={x}>{x}</li>)}</ul></section>}{r.projects?.length>0&&<section><h2 className={styles.sectionTitle}>{r.type==='search'?'Registry matches':'Project intelligence'}</h2><div className={styles.cards}>{r.projects.map(p=><Card key={p.id} p={p}/>)}</div></section>}{r.dependencies?.some(x=>x.items.length)&&<section><h2 className={styles.sectionTitle}>Dependencies</h2><div className={styles.deps}>{r.dependencies.filter(x=>x.items.length).map(x=><article key={x.plugin.id}><strong>{x.plugin.name}</strong><ul>{x.items.map(d=><li key={d.name}>{d.project?<Link to={d.project.profile}>{d.name}</Link>:d.name}</li>)}</ul></article>)}</div></section>}{r.type==='doctor'&&<section className={styles.doctor}><div><small>Next best action</small><h2>Continue in Sentinel Doctor</h2><p>Add versions, symptoms, logs, and repair rules.</p></div><Link className="button button--primary" to="/doctor">Open Doctor →</Link></section>}<div className={styles.source}>Source: Sentinel Unified Registry · Local browser engine · No external AI API</div></div>}
function App(){const[q,setQ]=useState(''),[r,setR]=useState(null),[history,setHistory]=useState([]);const related=useMemo(()=>r?.mentions?.length?[`What version of ${r.mentions[0].name} should I use?`,`What does ${r.mentions[0].name} require?`,`Is ${r.mentions[0].name} in the Golden Build?`]:expertExamples.slice(0,3),[r]);function ask(v=q){const clean=v.trim();if(!clean)return;const ans=answerExpertQuestion(clean);setR(ans);setQ(clean);setHistory(h=>[{q:clean,v:ans.verdict},...h.filter(x=>x.q!==clean)].slice(0,6));}return <Layout title="Sentinel Expert" description="Registry-grounded LSPDFR answers"><main className={styles.page}><header className={styles.hero}><div><small>Sentinel Intelligence Layer · Step 1</small><Heading as="h1">Ask Sentinel.</Heading><p>Structured answers from Project Sentinel data—without invented compatibility claims or a paid API.</p><section><span>59 registry projects</span><span>Compatibility reasoning</span><span>Dependency lookup</span><span>Doctor routing</span></section></div></header><div className={styles.layout}><aside className={styles.sidebar}><section><b>Try a verified question</b>{expertExamples.map(x=><button key={x} onClick={()=>ask(x)}>{x}</button>)}</section>{history.length>0&&<section><b>Session history</b>{history.map(x=><button key={x.q} onClick={()=>ask(x.q)}><strong>{x.q}</strong><small>{x.v}</small></button>)}</section>}</aside><section className={styles.main}><div className={styles.ask}><textarea rows="3" maxLength="500" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask();}}} placeholder="Ask about a plugin, version, dependency, conflict, category, or crash…"/><footer><span>{q.length}/500 · Enter to ask</span><button disabled={q.trim().length<3} onClick={()=>ask()}>Ask Sentinel</button></footer></div><Result r={r}/>{r&&<section className={styles.related}><b>Related questions</b><div>{related.map(x=><button key={x} onClick={()=>ask(x)}>{x}</button>)}</div></section>}</section></div></main></Layout>}
export default function SentinelAI(){return <BrowserOnly fallback={<Layout title="Sentinel Expert"><main className="container margin-vert--xl">Loading Sentinel intelligence…</main></Layout>}>{()=><App/>}</BrowserOnly>}
